### ISSUE TITLE
Trying to get demo running

### ISSUE THREAD

**Issue by jake3991** [saeedghsh/Map-Alignment-2D#2]
Hello! 

This is some pretty amazing work, I'm hoping to use it as a basis for some robotics research I'm doing myself. I am however, having some issues getting the demo to run take a look at my error trace below. I followed your instructions as per the repo and installed your other repo, arrangement. Looks like there is an skimage warning and then an actual error to do with networkx, any ideas?

/home/jake/.local/lib/python2.7/site-packages/skimage/transform/radon_transform.py:58: UserWarning: The default of `circle` in `skimage.transform.radon` will change to `True` in version 0.15.
  warn('The default of `circle` in `skimage.transform.radon` '
Traceback (most recent call last):
  File "demo.py", line 139, in <module>
    src_results['arrangement'], src_arr_t = mapali._construct_arrangement(src_results, arr_config)
  File "/home/jake/Desktop/Map-Alignment-2D/map_alignment/map_alignment.py", line 413, in _construct_arrangement
    arrange = arr.Arrangement(data['traits'], config)
  File "/home/jake/.local/lib/python2.7/site-packages/arrangement/arrangement.py", line 697, in __init__
    self._decompose()
  File "/home/jake/.local/lib/python2.7/site-packages/arrangement/arrangement.py", line 1033, in _decompose
    faces = self._decompose_graph(sg)
  File "/home/jake/.local/lib/python2.7/site-packages/arrangement/arrangement.py", line 1646, in _decompose_graph
    face_tmp = [ allHalfEdgeIdx[openListIdx] ]
  File "/home/jake/.local/lib/python2.7/site-packages/networkx/classes/reportviews.py", line 1106, in __getitem__
    u, v, k = e
TypeError: 'int' object is not iterable

**Comment by saeedghsh** [comment]
Hi @jake3991 , Thank you for your interest in this work and raising the issue.

Please accept my apologies for a very late response, I have been very overwhelmed recently and can't find the time to investigate this issue. I will try to find some time this weekend and fix the issue.

Sorry again for the tardiness.

**Comment by saeedghsh** [comment]
I will have to try it myself, but I have a hunch it has something to do with the changed interface of the `networkx` from version 1 to 2. Have you tried enforcing the old version of the networkx in the `requirement.txt`?

PS: `networkx >= 1.10` -> `networkx == 1.10`

**Comment by saeedghsh** [comment]
Hello again @jake3991 

There has been another issue rising in the other repo (`arrangement`, which this repo depends on).
https://github.com/saeedghsh/arrangement/issues/3#issuecomment-768500746

As I guessed, that one (and most probably this one) is due to changed API of `networkx`. The short term solution is forcing the pip to install older `networkx`.

Short term solution, unfortunately not sure when, will require adaptation of the code to the `networkx` version bump.
